### ISSUE TITLE
FEATURE REQUEST: Container image for keycloak version 14

### ISSUE THREAD

**Issue by DavidTheSysAdmin** [bitnami/bitnami-docker-keycloak#13]
Keycloak version 14 is out and stable. We would like to start testing this in our environment. Any chance a container image with keycloak version 14 will be available soon?

**Comment by migruiz4** [comment]
Hi @DavidTheSysAdmin,

Thank you for your feature request.
We are aware of the new Keycloak major version and we will work to release a docker image for this new version.

I can't give an ETA, but we will make it happen as soon as possible.

**Comment by beltran-rubo** [comment]
@DavidTheSysAdmin Keycloak 14 is now available in the repository, it was added on July the 7th.
