### ISSUE TITLE
unable to deploy

### ISSUE THREAD

**Issue by ashishkpaul** [bitnami/bitnami-docker-keycloak#15]
root@ldap:~/keyclock# docker --version
Docker version 20.10.7, build f0df350

root@ldap:~/keyclock#  docker run --name keycloak bitnami/keycloak:latest
Unable to find image 'bitnami/keycloak:latest' locally
latest: Pulling from bitnami/keycloak
2e4c6c15aa52: Pull complete 
61eeb2e3e2e1: Pull complete 
dfbff4332d4d: Pull complete 
65eb9f427218: Pull complete 
4cac4aedb1ee: Pull complete 
b46dcfe206f5: Pull complete 
f5a8166aa80f: Pull complete 
e2c10e1a2042: Pull complete 
8cb169fe016b: Pull complete 
be68bbe0f7af: Pull complete 
Digest: sha256:c9d857595234c324e100522332dc4256a024fbc689b3eb93bfa83d8cce68a7a4
Status: Downloaded newer image for bitnami/keycloak:latest
keycloak 07:38:10.16 
keycloak 07:38:10.16 Welcome to the Bitnami keycloak container
keycloak 07:38:10.17 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-keycloak
keycloak 07:38:10.17 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-keycloak/issues
keycloak 07:38:10.17 
keycloak 07:38:10.17 INFO  ==> ** Starting keycloak setup **
keycloak 07:38:10.18 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 07:38:10.19 INFO  ==> Trying to connect to PostgreSQL server postgresql...
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
cannot resolve host "postgresql": lookup postgresql on 8.8.8.8:53: no such host
keycloak 07:39:00.54 ERROR ==> Unable to connect to host postgresql

**Comment by javsalgar** [comment]
Hi,

It seems that you are missing the postgresql instance to connect. Could you try using the docker-compose file here?

https://github.com/bitnami/bitnami-docker-keycloak/blob/master/14/debian-10/docker-compose.yml

**Comment by daurrutia** [comment]
Maybe this should be reopened.

https://github.com/bitnami/bitnami-docker-keycloak#tldr Doesn't really specify an existing postgres container running.

e.g., `docker run -p 8080:8080 jboss/keycloak`  comes up with an internal DB.

**Comment by carrodher** [comment]
Please note you are not using this container image (`bitnami/keycloak`) but a different one (`jboss/keycloak`), in the same way, the PostgreSQL instance is not part of the keycloak container but should be deployed in a separate way, for example using docker-compose

**Comment by daurrutia** [comment]
I understand, docker compose is the way to go. 
It's just not clearly stated on the README (or on the dockerhub page) that the quickest way to launch `bitnami/keycloak` is with docker compose. There is a `docker run` example given in the [TLDR section](https://github.com/bitnami/bitnami-docker-keycloak/blob/master/README.md#tldr ) that is a bit misleading.

**Comment by javsalgar** [comment]
Hi,

Thanks for the input! I will forward this feedback to the documentation team.
