### ISSUE TITLE
Keystore not found with TLS settings enabled

### ISSUE THREAD

**Issue by jgallucci32** [bitnami/bitnami-docker-keycloak#2]
**Description**
When starting container with TLS settings enabled and keystore and truststore files provided, the application server fails to detect the keystore and uses a self-signed certificate instead. Here is the exact error message
```
18:33:36,650 WARN  [org.jboss.as.domain.management.security] (MSC service thread 1-2) WFLYDM0111: Keystore /opt/bitnami/keycloak/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self signed certificate for host localhost
```

**Steps to reproduce the issue:**

1. Create JKS files per [instructions](https://github.com/bitnami/bitnami-docker-keycloak/tree/11.0.3-debian-10-r27#tls-encryption) and copy to `/opt/bitnami/keycloak/certs`
2. Mount `/opt/bitnami/keycloak/certs` volume to container
3. Set environment variables for `KEYCLOAK_ENABLE_TLS` `KEYCLOAK_TLS_KEYSTORE_FILE` `KEYCLOAK_TLS_TRUSTSTORE_FILE` as described in documentation
4. Start container with Mount and ENV parameters

**Describe the results you received:**
Keycloak generates self-signed certificate for `localhost` and does not use the custom certificate from the keystore

**Describe the results you expected:**
Keycloak should be accessible via https using the custom certificate provided by the keystore

**Additional information you deem important (e.g. issue happens only occasionally):**
This is currently being deployed as a Kubernetes pod using the bitnami helm chart.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:03:45 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:02:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 40
  Running: 33
  Paused: 0
  Stopped: 7
 Images: 40
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.el7.x86_64
 Operating System: Red Hat Enterprise Linux Server 7.8 (Maipo)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 14.53GiB
 Name: vc3-test-k8s-2
 ID: HEK3:KES4:HWQS:AJ7K:YZYD:5LNT:KJZY:UBHB:4GQD:HZUD:TWY6:3323
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Red Hat Enterprise Linux 7.8
Rancher Kubernetes 17.5.1

**Comment by jgallucci32** [comment]
Running the container in debug I noticed the following error. It does not look like the JBoss CLI is applying the TLS settings because the spi for truststore is missing
```
WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:
Step: step-8
Operation: /subsystem=keycloak-server/spi=truststore/provider=file:add(enabled=true,properties={file => /opt/bitnami/keycloak/certs/keycloak.truststore.jks, password => changeit, hostname-verification-policy => "WILDCARD", disabled => "false"})
Failure: WFLYCTL0175: Resource [
    ("subsystem" => "keycloak-server"),
    ("spi" => "truststore")
] does not exist; a resource at address [
    ("subsystem" => "keycloak-server"),
    ("spi" => "truststore"),
    ("provider" => "file")
] cannot be created until all ancestor resources have been added
```

**Comment by jgallucci32** [comment]
Referencing the [Keycloak Documentation](https://www.keycloak.org/docs/latest/server_installation/index.html#add-a-new-spi-and-a-provider) I was able to get past this error by adding the following statement to `/opt/bitnami/scripts/libkeycloak.sh`
```
subsystem=keycloak-server/spi=truststore/:add
```

However, additional errors are now presented which need to be resolved next
```
WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:
Step: step-2
Operation: /subsystem=elytron/server-ssl-context=kcSSLContext:add(key-manager=kcKeyManager)
Failure: WFLYCTL0369: Required capabilities are not available:
    org.wildfly.security.key-manager.kcKeyManager; Possible registration points for this capability:
		/subsystem=security/elytron-key-manager=*
		/subsystem=elytron/key-manager=*
Step: step-5
Operation: /subsystem=elytron/trust-manager=kcTrustManager:add(key-store=kcTrustStore)
Failure: WFLYCTL0369: Required capabilities are not available:
    org.wildfly.security.key-store.kcTrustStore; Possible registration points for this capability:
		/subsystem=elytron/key-store=*
		/subsystem=elytron/ldap-key-store=*
		/subsystem=elytron/filtering-key-store=*
		/subsystem=security/elytron-key-store=*
		/subsystem=security/elytron-trust-store=*
```

**Comment by marcosbc** [comment]
Hi @jgallucci32, it seems you are right and there may be an issue in the initialization logic. I'm going to create an internal task and include the info. Unfortunately I won't be able to provide an ETA for when this would be fixed, but if you manage to find the solution, feel free send a PR as we'd be glad to review and help with the release.

>Referencing the [Keycloak Documentation](https://www.keycloak.org/docs/latest/server_installation/index.html#add-a-new-spi-and-a-provider) I was able to get past this error by adding the following statement to `/opt/bitnami/scripts/libkeycloak.sh`
>
>```
>subsystem=keycloak-server/spi=truststore/:add
>```

**Comment by FraPazGal** [comment]
Hello @jgallucci32,

We released a [new version](https://github.com/bitnami/bitnami-docker-keycloak/commit/41c8a87191302be3d375edd91dea70300f2ce0c9) that fixes the container's TLS issues. Could you give it a try and confirm everything is working as expected? Thanks in advance!

**Comment by jgallucci32** [comment]
Thanks @FraPazGal that is awesome. Saw the commit, great find on those typos. I looked over that config for hours and didn't catch those. The good news is I can now get past those error and Wildfly is now looking for those custom keystore files.

The bad news is there are still file permission issues getting the container to properly read those certificates. If we could remove the requirement (which we said was a niche case anyways) to have a different cert for each replica (keystore-[0,1,2]) then the helm chart could be solved easily. If not then I'm still working through a method to get this to work.

**Comment by jgallucci32** [comment]
My third option of symbolic links with a configMap is out. Kubernetes mounts configMaps volumes as read-only by design. See https://github.com/kubernetes/kubernetes/issues/62099 for more details.

The more I dig into this the less I understand the need for the niche use case of unique certificates per replica. Kubernetes is designed to scale applications through replica sets and they need to be stateless. By creating a unique cert per replica set the app is no longer stateless and will only be able to scale by the number of pre-determined certs which have been configured. This goes against the principles of Kubernetes replicas which is why I feel like I keep running into these limitations.

Considering the container itself was non-functional until recently, I do not expect there to be any impact as it wasn't possible to configure Keycloak on K8s in this manner (it still technically isn't until we fix it with a PR). My recommendation is to update the instructions to specify only a single ssl cert/key pair as the server SSL cert rather than have one per replica.

**Comment by FraPazGal** [comment]
Hello @jgallucci32,

I'm glad this issue got solved. Let's continue the chart fix discussion on the PR thread.
