### ISSUE TITLE
FEATURE REQUEST: Add possibility to send JDBC_PARAMS to connection string for Portgres

### ISSUE THREAD

**Issue by vl4d1m1r4** [bitnami/bitnami-docker-keycloak#21]
In the JBoss Keycloak docker image there is possibility to specify additional JDBC Parameters via the JDBC_PARAMS environment variable. This is explained in the README of the [Keycloak Docker Hub](https://hub.docker.com/r/jboss/keycloak/ ) in the Specify JDBC parameters chapter. 

I looked through the source code in [`libkeycloak.sh`](https://github.com/bitnami/bitnami-docker-keycloak/blob/5384a1bf1d5516e3fbc258dc3e822747928af04c/15/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh#L98) for this image and I can see that the only parameter that is explicitly set is `useSSL` which is controlled with the `KEYCLOAK_DATABASE_TLS` environment variable. This is not enough for some use cases, like when certificates are used to connect to the db, because we don't want to use a JKS, but use the parameters for overriding the `sslrootcert`, `sslcert` and `sslkey` and also use `sslmode=verify-full` described in the [PostgreSQL SSL Support](https://www.postgresql.org/docs/13/libpq-ssl.html)

Can you please look into this and if it is feasible to be included?

Thanks

**Comment by alemorcuq** [comment]
Thanks for the suggestion, @vl4d1m1r4! I think this would be a nice addition to the container. Would you be interested in contributing with a PR?

**Comment by vl4d1m1r4** [comment]
Sure, I will try to do it in a few days. I have a few open questions, do you have any suggestion what should i do with the `KEYCLOAK_DATABASE_TLS` support? If I include an additional environment variable for the new functionality this variable will be obsolete so I can remove it, but it also triggers a few checks for the keystore controlling variables. This will also introduce a breaking change as everyone that is using the image will need to switch to the new environment variable to set useSSL. Another thing is that I went through the postgre [jdbc driver configuration params](https://jdbc.postgresql.org/documentation/head/connect.html) and I can't find the `useSSL` property anywhere. SSL is enabled by providing any value to the `ssl` property (even `ssl=false` will enable it) since just the mere presence of it is treated as true as explained in the docs.

**Comment by alemorcuq** [comment]
Thanks a lot for the PR, @vl4d1m1r4!
