### ISSUE TITLE
How to set welcome theme

### ISSUE THREAD

**Issue by Ognian** [bitnami/bitnami-docker-keycloak#23]
The official docker keycloak container has an environment variable KEYCLOAK_WELCOME_THEME to set the default welcome theme.
The corresponding cli is https://github.com/keycloak/keycloak-containers/blob/master/server/tools/cli/theme.cli 

Any chance to get the env var here added too?

Thanks
Ognian

**Comment by Mauraza** [comment]
Hi @Ognian,

We are open to a contribution. You can create a PR with a solution that we will be happy to review.

**Comment by Ognian** [comment]
@Mauraza unfortunately I have do idea how to fix this.
I tried adding `KEYCLOAK_EXTRA_ARGS="-Dkeycloak.theme.welcomeTheme=xxxx"` but this did not work...
Changing the config files would be an option but for the moment I simply don't know how to do it...

**Comment by Mauraza** [comment]
Hi @Ognian,

Maybe this PR https://github.com/bitnami/bitnami-docker-keycloak/pull/8 could help you.

**Comment by Ognian** [comment]
@Mauraza no, this one only changes environment vars which are then added to the command line, this would work if the `KEYCLOAK_EXTRA_ARGS="-Dkeycloak.theme.welcomeTheme=xxxx"` workaround worked...

**Comment by Mauraza** [comment]
Did you try something like this `KEYCLOAK_EXTRA_ARGS="-Dkeycloak.theme.welcomeTheme.name=keycloak"`?

**Comment by Ognian** [comment]
Just tested this -> no success
Also tried: `KEYCLOAK_EXTRA_ARGS="-Dkeycloak-server.theme.welcomeTheme.name=keycloak"` -> no success
Also tried: `KEYCLOAK_EXTRA_ARGS="-Dkeycloak-server.theme.welcomeTheme=keycloak"` -> no success

**Comment by Ognian** [comment]
I've set BITNAME_DEBUG to true but searching naively true the output I can't see any output with "welcomeTheme"
is there a better way to debug this?

**Comment by Ognian** [comment]
created also https://issues.redhat.com/browse/KEYCLOAK-19358

**Comment by mshenhera** [comment]
Faced the same issue. Workaround that works for me:
```
initdbScripts:
    theme.sh: |
      #!/bin/bash
      info "Configuring My theme"
      KEYCLOAK_CONF_FILE="standalone-ha.xml"
      debug_execute jboss-cli.sh <<EOF
      embed-server --server-config=${KEYCLOAK_CONF_FILE} --std-out=discard
      batch
      /subsystem=keycloak-server/theme=defaults:write-attribute(name=welcomeTheme,value=my_theme_name)
      /subsystem=keycloak-server/theme=defaults:write-attribute(name=default,value=my_theme_name)
      run-batch
      stop-embedded-server
      EOF
```

**Comment by Mauraza** [comment]
Hi @mshenhera,

Thanks for sharing this workaround!!

**Comment by Ognian** [comment]
@mshenhera thank you so much! It worked!

**Comment by Ognian** [comment]
For those who find the above solution here:
After some testing I noticed that when setting the default theme to i.e `my_theme_name` keycloak searches for the **account** theme `my_theme_name.v2` as the theme name (all other types seam correct searching for `my_theme_name`). 
This seems to be a keycloak problem...

The easiest workaround is to manually set the **account** to my_theme_name via admin UI...

**Comment by Ognian** [comment]
Sorry for spamming this, but I found also the reason for the above: https://issues.redhat.com/browse/KEYCLOAK-16869

**Comment by Mauraza** [comment]
Hi @Ognian,

Thanks for sharing all this information, so if someone has the same problem this thread can find all the info.

**Comment by desarrolladorsenior1** [comment]
> Faced the same issue. Workaround that works for me:
> 
> ```
> initdbScripts:
>     theme.sh: |
>       #!/bin/bash
>       info "Configuring My theme"
>       KEYCLOAK_CONF_FILE="standalone-ha.xml"
>       debug_execute jboss-cli.sh <<EOF
>       embed-server --server-config=${KEYCLOAK_CONF_FILE} --std-out=discard
>       batch
>       /subsystem=keycloak-server/theme=defaults:write-attribute(name=welcomeTheme,value=my_theme_name)
>       /subsystem=keycloak-server/theme=defaults:write-attribute(name=default,value=my_theme_name)
>       run-batch
>       stop-embedded-server
>       EOF
> ```

I'm trying this in my `docker-compose.yml` but I get a Permission Denied error:

```
my_keycloak | keycloak 19:30:50.13 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
my_keycloak | /opt/bitnami/scripts/libkeycloak.sh: line 427: /docker-entrypoint-initdb.d/theme.sh: Permission denied
my_keycloak exited with code 126
```

This is the content of `theme.sh`:

```
#!/bin/bash
info "Configuring the talentum theme"
KEYCLOAK_CONF_FILE="standalone-ha.xml"
debug_execute jboss-cli.sh <<EOF
embed-server --server-config=${KEYCLOAK_CONF_FILE} --std-out=discard
batch
/subsystem=keycloak-server/theme=defaults:write-attribute(name=welcomeTheme,value=talentum)
/subsystem=keycloak-server/theme=defaults:write-attribute(name=default,value=talentum)
run-batch
stop-embedded-server
EOF
```

And this is how I mount the directory: `./_resources/init-scripts:/docker-entrypoint-initdb.d`

@Mauraza Could you please nudge me in the right direction? Is `docker-entrypoint-initdb.d` intended for shell scripts?

Thank you

**Comment by Mauraza** [comment]
Hi @Ognian,

```
my_keycloak | /opt/bitnami/scripts/libkeycloak.sh: line 427: /docker-entrypoint-initdb.d/theme.sh: Permission denied
```
It seems a permission problem, so could you check the permission of the script?

**Comment by Ognian** [comment]
Hmm don't know if this helps:
I'm running in a k8s environment: theme.sh is a link
`
/docker-entrypoint-initdb.d/theme.sh
/docker-entrypoint-initdb.d$ ls -ltr
total 0
lrwxrwxrwx 1 root root 15 Sep 23 10:43 theme.sh -> ..data/theme.sh
`
Looks like data was linked to this dir:
`
/docker-entrypoint-initdb.d/..2021_09_23_10_43_59.460597755/theme.sh
$ ls -als /docker-entrypoint-initdb.d/..2021_09_23_10_43_59.460597755/theme.sh
4 -rw-r--r-- 1 root 1001 403 Sep 23 10:43 /docker-entrypoint-initdb.d/..2021_09_23_10_43_59.460597755/theme.sh
`
In my case everything works correctly, don't know how this could help @desarrolladorsenior1 ?

**Comment by desarrolladorsenior1** [comment]
Thank you for your help, @Mauraza and @Ognian 

I had to give execution rights to my shell script: `chmod a+x theme.sh`. It's working now 🎉, but I had to adjust it because commands `info` and `debug_execute` were not found:

```bash
talentum_keycloak | keycloak 14:55:16.64 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d ...
talentum_keycloak | /docker-entrypoint-initdb.d/theme.sh: line 2: info: command not found
talentum_keycloak | /docker-entrypoint-initdb.d/theme.sh: line 4: debug_execute: command not found
```

This is the new file:

```bash
#!/bin/bash
echo "Configuring the my_theme_name theme"
KEYCLOAK_CONF_FILE="standalone-ha.xml"
sh /opt/bitnami/keycloak/bin/jboss-cli.sh <<EOF
embed-server --server-config=${KEYCLOAK_CONF_FILE} --std-out=discard
batch
/subsystem=keycloak-server/theme=defaults:write-attribute(name=welcomeTheme,value=my_theme_name)
/subsystem=keycloak-server/theme=defaults:write-attribute(name=default,value=my_theme_name)
run-batch
stop-embedded-server
EOF
```

And this is the output:
<details>
<pre>
talentum_keycloak | Configuring the my_theme_name theme
talentum_keycloak | You are disconnected at the moment. Type 'connect' to connect to the server or 'help' for the list of supported commands.
talentum_keycloak | [disconnected /] embed-server --server-config=standalone-ha.xml --std-out=discard
talentum_keycloak | WARNING: An illegal reflective access operation has occurred
talentum_keycloak | WARNING: Illegal reflective access by org.wildfly.extension.elytron.SSLDefinitions (jar:file:/opt/bitnami/keycloak/modules/system/layers/base/org/wildfly/extension/elytron/main/wildfly-elytron-integration-15.0.1.Final.jar!/) to method com.sun.net.ssl.internal.ssl.Provider.isFIPS()
talentum_keycloak | WARNING: Please consider reporting this to the maintainers of org.wildfly.extension.elytron.SSLDefinitions
talentum_keycloak | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
talentum_keycloak | WARNING: All illegal access operations will be denied in a future release
talentum_keycloak | [standalone@embedded /] batch
talentum_keycloak | [standalone@embedded / #] /subsystem=keycloak-server/theme=defaults:write-attribute(name=welcomeTheme,value=my_theme_name)
talentum_keycloak | [standalone@embedded / #] /subsystem=keycloak-server/theme=defaults:write-attribute(name=default,value=my_theme_name)
talentum_keycloak | [standalone@embedded / #] run-batch
talentum_keycloak | The batch executed successfully
talentum_keycloak | [standalone@embedded /] stop-embedded-server
talentum_keycloak | [disconnected /]
</pre>
</details>

**Comment by Mauraza** [comment]
Hi @desarrolladorsenior1,

I'm glad it's working!!

**Comment by Ognian** [comment]
Unfortunately this issue still makes problems:

- If on a clean k8s cluster there is any `initdbScripts:` entry (even only a script wich echoes "Hello world") this prevents keycloak from properly being initialized and start up.
- If we start without `initdbScripts:`and add later on add the above ìnitdbScripts` everything is fine.

Since I need to bootstrap everything without manual intervention this behavior is a big Problem...
 
It looks like something is called in the absence of initdbScripts which is only important at the very first run...

**Comment by Mauraza** [comment]
Hi @Ognian,

I try with the chart https://github.com/bitnami/charts/tree/master/bitnami/keycloak and everything goes right. Could you share more information about this? You could set `image.debug` to [true](https://github.com/bitnami/charts/blob/3da431157cb73a6c3d9298657ab307b55a13c306/bitnami/keycloak/values.yaml#L77) if appears more information.

**Comment by Ognian** [comment]
@Mauraza I've uploaded the 2 logs, the first one (...68.log) is the good case and the second (...28.log) the bad case
[default-keycloak-0-1637332143027792828.log](https://github.com/bitnami/bitnami-docker-keycloak/files/7570928/default-keycloak-0-1637332143027792828.log)
[default-keycloak-0-1637320692822203268.log](https://github.com/bitnami/bitnami-docker-keycloak/files/7570929/default-keycloak-0-1637320692822203268.log)
going thru them with a diff viewer it looks like the jboss/keycloak configuration is a different one when there is an `initdbScripts:` entry.
<img width="1880" alt="image" src="https://user-images.githubusercontent.com/1231174/142643678-74d8a0f6-2c62-4921-a53d-7e2542996587.png">

In the above diff screenshot we see that anything is the same up to the point where my initdbScripts script is called.
The script echoes 'Ogi's test.sh' and echos the environment...
<img width="1880" alt="image" src="https://user-images.githubusercontent.com/1231174/142644176-dc272d25-69b4-4111-8ad1-e01785fc1f5e.png">
After that keycloak is starting, but as you can see at ServerService Thread Pool -- 14 vs. ServerService Thread Pool -- 2
the config starts to diverge

**Comment by Ognian** [comment]
It looks like with an `initdbScript` the `standalone-ha-default.xml ` is used which has no postgres driver, instead of the `standalone-ha.xml` which is the correct one...

**Comment by Ognian** [comment]
I think I found the problem:
I'm using agrocd for continuous deployment. When removing an app (this is i.e a helm deployment) all resources on the cluster are removed, but although shown the **pvc** is NOT removed and when redeploying it is reused...
So the solution is to manually check if the pvc already exists and delete it.
https://github.com/argoproj/argo-cd/issues/3041 
@Mauraza thanks for always responding to my posts

**Comment by Mauraza** [comment]
Hi @Ognian,

I'm glad you found the error, do not hesitate to write us back if you have any other questions.

**Comment by lizhouyang** [comment]
i think i got the problem，the docker have't the permission to read the  sh file

**Comment by 5RK7N** [comment]
On version 18.0.0, I am able to configure the welcome theme only use `externalStartupArgs`:
```
extraStartupArgs: "--spi-theme-welcome-theme=my_theme"
```

Reference: https://www.keycloak.org/docs/latest/server_development/#configuring-a-theme
