### ISSUE TITLE
Keycloak kcadm tool does not work

### ISSUE THREAD

**Issue by duhow** [bitnami/bitnami-docker-keycloak#28]
**Description**

Cannot execute **kcadm.sh** to admin the Keycloak server. This does work with `jboss/keycloak` image.
Lack of `$HOME` directory for UID user 1001. Only works if I use `root` user, but I'd like to avoid this due to security concerns.

**Steps to reproduce the issue:**

1. `kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin`

**Describe the results you received:**

```I have no name!@keycloak-0:/$ kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin
Logging into http://localhost:8080/auth as user admin of realm master
Enter password: *************************
Failed to create config file: /?/.keycloak/kcadm.config
```

**Describe the results you expected:**

No error on creating `kcadm.config` file on default folder.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

Using image `bitnami/keycloak:15.0.2-debian-10-r4`

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by rafariossaa** [comment]
Hi,
  Did you have the chance to test it ?

**Comment by duhow** [comment]
Sorry, not yet. I'll check this week.

**Comment by duhow** [comment]
Got it! Problem was `workingDir`, it has to be changed to `/tmp` or just change directory with a command.
Since the image runs by default on `/`, you can't run this command directly upon container creation.

If you think there's nothing else to do, feel free to close this ticket.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for coming back and sharing your findings.
  I am glad you were able to figure it out.
  I am closing this issue.
