### ISSUE TITLE
(QUESTION) Kubernetes redirecting to http in spite of using PROXY_ADDRESS_FORWARDING true

### ISSUE THREAD

**Issue by gtejeda** [bitnami/bitnami-docker-keycloak#32]
Could anybody please help?
I deployed this image on Kubernetes, it works beautifully on local development environment, but on production the redirect_uri is set to http instead of https.

I've tried these variables with no luck:
          - name: PROXY_ADDRESS_FORWARDING
            value: 'true'
          - name: KEYCLOAK_EXTRA_ARGS
            value: "-Dkeycloak.adminUrl=https://ourdomain/auth -Dkeycloak.frontendUrl=https://ourdomain/auth"

Any help would be GREATLY appreciated

**Comment by alvneiayu** [comment]
Hi @gtejeda 

Did you test this section?

https://github.com/bitnami/charts/tree/master/bitnami/keycloak#use-with-ingress-offloading-ssl

Including also the KEYCLOAK_FRONTEND_URL.

Thanks a lot

Álvaro

**Comment by gtejeda** [comment]
Thanks for the reply @alvneiayu, yes, I also tried with that parameter added without luck:
` 
       - name: KEYCLOAK_CREATE_ADMIN_USER
          value: 'true'
        - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
          value: 'true'
        - name: KEYCLOAK_FRONTEND_URL
          value: https://xxx.com/auth
`

I think I just found the core issue:
12:59:22,743 WARN  [org.keycloak.events] (default task-14) type=LOGIN_ERROR, realmId=easyauto, clientId=easyauto-devinstance-webcore, userId=null, ipAddress=10.0.1.215, error=invalid_redirect_uri, redirect_uri=http://xxxx.com/signin-oidc

I found this in the server logs... ipAddress is an internal ip, and not the user ip; I'm currently investigatin how to forward this information from the load balancer.

Will reply, if I manage to fix the issue

**Comment by gtejeda** [comment]
I now have a server which is redirecting my ipAddress properly, and I'm still unable to get it working. :(
I know this must be a rather simple issue that I'm missing, but I'm at a complete loss, so any help is greatly appreciated

**Comment by alvneiayu** [comment]
hi @gtejeda 

maybe this case could help you:

https://stackoverflow.com/questions/47181821/using-keycloak-behind-a-reverse-proxy-could-not-open-admin-loginpage-because-mi

Thanks a lot

Álvaro
