### ISSUE TITLE
keycloak image on AWS ECS on fargate

### ISSUE THREAD

**Issue by tomaskovacik** [bitnami/bitnami-docker-keycloak#33]
Hello, my question, is ECS@fargate supported platform to run your docker images?
I got strange errors, 1st of all:

if I did not specify KEYCLOAK_BIND_ADDRESS=0.0.0.0 as container variable (which should be by default set to 
0.0.0.0: "KEYCLOAK_BIND_ADDRESS: Keycloak bind address. Default: 0.0.0.0.")
container exited with an error

```bash
INFO [0m ==> ** Starting keycloak setup **
hostname: Name or service not known
[0m ==> Validating settings in KEYCLOAK_* env vars...
/opt/bitnami/scripts/libvalidations.sh: line 196: 1: ip is missing
```

when KEYCLOAK_BIND_ADDRESS=0.0.0.0 is set, everything goes well until this happens when initializing JBoss:

```bash
ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 55) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "transactions")]) - failure description: "WFLYCTL0419: 'b6d3c5eb6c744d479144603421f332e4-2060237147' is an invalid value for parameter node-identifier. Values must have a maximum length of 23 bytes"
```

google find that in here you are doing  truncate to 20chars before the start of JBoss server

https://github.com/bitnami/charts/blob/c6ff51cdfc1791124ecf2a2ecfa677a6e46bf0b0/bitnami/keycloak/templates/_helpers.tpl

while I was writing this i was also searching again and again, so I stepped  over this post: https://stackoverflow.com/questions/48809333/how-to-configure-hostname-in-ecs-fargate-task-definition

so hostname in fargate is "<TaskId>-<suffixNumber"  which is over 23chars, so this need to be fixed 

later I fix node-identifier error with HOSTNAME=TEST in command  which fix this error but another error raises up:

```bash
[0m[31m19:30:56,361 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 58) MSC000001: Failed to start service org.wildfly.clustering.jgroups.channel.ee: org.jboss.msc.service.StartException in service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.net.BindException: [UDP] /0.0.0.0 is not a valid address on any local network interface
```

At this time it was clear that I must somehow get container IP from  ${ECS_CONTAINER_METADATA_URI_V4}  
more here: https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html

but this was not possible because of limited utils installed in the container, so I use crude cat /etc/hosts method :)

here is my final hack:

```bash
Entry point  ["sh","-c"]
Command  ["export KEYCLOAK_BIND_ADDRESS=`grep 10.0.0 /etc/hosts` && export HOSTNAME=`echo ${HOSTNAME} |cut -d\\- -f2` && /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh""]
```
The only problem is that all my URLs point to default-host:8080, so exporting HOSTNAME is not so best idea :)

thx

**Comment by Mauraza** [comment]
Hi @tomaskovacik.

Did you try to use these variables https://github.com/bitnami/bitnami-docker-keycloak/#port-and-address-binding?

**Comment by tomaskovacik** [comment]
hello, yes try it, no luck ... my current vars are:

KEYCLOAK_ADMIN_PASSWORD | xxxxx
KEYCLOAK_ADMIN_USER | admin
KEYCLOAK_CREATE_ADMIN_USER | TRUE
KEYCLOAK_DATABASE_HOST | xxxxxx.eu-central-1.rds.amazonaws.com
KEYCLOAK_DATABASE_NAME | xxxxx
KEYCLOAK_DATABASE_PASSWORD | xxxxx
KEYCLOAK_DATABASE_PORT | 5432
KEYCLOAK_DATABASE_SCHEMA | kc
KEYCLOAK_DATABASE_USER | xxxxx
KEYCLOAK_MANAGEMENT_PASSWORD | xxxxxx
KEYCLOAK_MANAGEMENT_USER | xxxx
PROXY_ADDRESS_FORWARDING | true
REDIRECT_SOCKET | proxy-https


plus ones which are set in command :
Command  ["export KEYCLOAK_BIND_ADDRESS=`grep 10.0.0 /etc/hosts` && export HOSTNAME=`echo ${HOSTNAME} |cut -d\\- -f2` && /opt/bitnami/scripts/keycloak/entrypoint.sh /opt/bitnami/scripts/keycloak/run.sh""]

I even try to set KEYCLOAK_FRONTEND_URL ... without  success, everything works flawlessly in docker on the standard Linux box

**Comment by tomaskovacik** [comment]
anyway I fix problem by using jboss/keycloak image
 no special parameters hacks required

if you are willing to try tofix this I can provide more support, for now fill free to close issue

**Comment by Mauraza** [comment]
Hi @tomaskovacik,

we are open to contribution if you want to create a PR with the change necessaries to run ECS@fargate, we will happy to review it.
