### ISSUE TITLE
(QUESTION) Use a custom build from Keycloak

### ISSUE THREAD

**Issue by svilenvul** [bitnami/bitnami-docker-keycloak#35]
We are trying to create a new docker image (to be used with Bitnami Helm chart) based on a custom fork of Keycloak integrating additional changes to the Keycloak core modules.

What is the recommended way to achieve this. Should we just extend the `bitnami/keycloak` image and overwrite keycloak distro with our custom build files?

Your guidance will be highly appreciated.

**Comment by cemckenzie** [comment]
Also interested in this, was unable to find the bitnami Keycloak source files that are used to create this distribution.

**Comment by javsalgar** [comment]
Hi,

Yes, feel free to replace the keycleoak files at /opt/bitnami/keycloak with your own files. We use the upstream keycloak files with the Wildfly bundled.

**Comment by marziman** [comment]
Hello @javsalgar 

last time we tried this, there we faced some permission issues with user, missing folders etc. Can you please give a bit more detailed guidance? Is it possible to describe it on docs? It would be highly appreciated.

Thank you!

**Comment by javsalgar** [comment]
Hi,

The details on the permissions set can be found in our postunpack.sh script. This is where we configure users and permissions: https://github.com/bitnami/bitnami-docker-keycloak/blob/master/15/debian-10/rootfs/opt/bitnami/scripts/keycloak/postunpack.sh

We open-sourced all the configuration files so it was for developers to check the operations performed in the container.

Note that we cannot provide support for a very specific keycloak distribution apart from the upstream one we bundle, but feel free to provide any feedback on the container scripts and even contribute with PRs.
