### ISSUE TITLE
15.1.1

### ISSUE THREAD

**Issue by 030** [bitnami/bitnami-docker-keycloak#37]
Could the packages be updated and bitnami/keycloak 15.1.1 be published?

**Comment by juan131** [comment]
Hi @030 

We're tracking new releases from https://www.keycloak.org/downloads.html and it seems the version **15.1.1** wasn't published there yet. Once the upstream project updates this website, our system will automatically detect the new version and proceed with the container release.

**Comment by marziman** [comment]
Hello @juan131 

how long does this take usually? 
KC v16.0 was released 2 days ago

**Comment by carrodher** [comment]
This version was released some days ago, see https://github.com/bitnami/bitnami-docker-keycloak/commit/339f8ba58fc98cf1557831e6f9597639e6dcb7e9; please feel free to reopen this issue if something is not working as expected.
