### ISSUE TITLE
Using Docker Secrets

### ISSUE THREAD

**Issue by candeemis** [bitnami/bitnami-docker-keycloak#39]
I was wondering if using docker secrets is already supported somehow, perhaps I missing something! I just wanted to provide usernames and passwords e.g db user and password through docker secrets, however I couldn't find any way in any documentation.

Your support would be highly appreciated.

**Comment by migruiz4** [comment]
Hi @candeemis,

Most of the containers in our catalog support providing env variables using `${env_name}_FILE`. 
Those environment variables can be configured with the path to a file containing the value for `$env_name`.

For example, `KEYCLOAK_PASSWORD` can be configured by mounting a file containing your password at `/mnt/example/keycloak_password` and then setting the env variable `KEYCLOAK_PASSWORD_FILE=/mnt/example/keycloak_password`.

`_FILE` environment variables can be configured using Docker secrets as described in the Docker documentation: https://docs.docker.com/engine/swarm/secrets/#advanced-example-use-secrets-with-a-wordpress-service

```
 docker service create \
     --name keycloak \
     --replicas 1 \
     --network keycloak \
     --publish published=8080,target=80 \
     --secret source=keycloak_password,target=keycloak_password \
     -e KEYCLOAK_PASSWORD_FILE="/run/secrets/keycloak_password" \
     bitnami/keycloak:latest
```
 
The environment variables that allow using the `_FILE` alternative are defined at `keycloak-env.sh`: https://github.com/bitnami/bitnami-docker-keycloak/blob/master/15/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh#L21-L85

**Comment by candeemis** [comment]
Hello @migruiz4, thanks for your response and the good news. It solves my problem. It would be even better if your kind words would be somewhere in a README, so that others can find them easily...

**Comment by migruiz4** [comment]
You are welcome @candeemis. I'm happy you found my solution helpful.

I agree that documenting the usage of the `*_FILE` variables in our README would be helpful so users can find it easier. I have created an internal task to cover it in the container READMEs or in our documentation.

If your question has been resolved, I will now proceed to close this issue.
