### ISSUE TITLE
Can I use mysql database? 

### ISSUE THREAD

**Issue by rushairer** [bitnami/bitnami-docker-keycloak#4]
Can I use mysql database? 

Thanks.

**Comment by marcosbc** [comment]
Hi @rushairer, unfortunately only PostgreSQL is supported, but you could always contribute the required changes to support MySQL/MariaDB as well.

Refer to [`libkeycloak.sh`](https://github.com/bitnami/bitnami-docker-keycloak/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh) for the related logic that checks for DB availability and configures the connection to the application.

**Comment by rushairer** [comment]
> @rushairer，您好，不幸的是仅支持PostgreSQL，但是您始终可以贡献所需的更改以支持MySQL / MariaDB。
> 
> 请参阅[`libkeycloak.sh`](https://github.com/bitnami/bitnami-docker-keycloak/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh)有关检查DB可用性并配置与应用程序的连接的相关逻辑。

Thanks, I made a fork for mysql,  but I have not add the mysql driver into the image. 
Just mount the driver file into /opt/bitnami/keycloak/modules/system/layers/base/com/mysql/jdbc/main/

Wait a few days to make a complete mirror when I have time.

**Comment by rushairer** [comment]
> Hi @rushairer, unfortunately only PostgreSQL is supported, but you could always contribute the required changes to support MySQL/MariaDB as well.
> 
> Refer to [`libkeycloak.sh`](https://github.com/bitnami/bitnami-docker-keycloak/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh) for the related logic that checks for DB availability and configures the connection to the application.

Thanks, I made a fork for mysql, but I have not add the mysql driver into the image.
Just mount the driver file into /opt/bitnami/keycloak/modules/system/layers/base/com/mysql/jdbc/main/

Wait a few days to make a complete mirror when I have time.

**Comment by vrtata** [comment]
> Hi @rushairer, unfortunately only PostgreSQL is supported, but you could always contribute the required changes to support MySQL/MariaDB as well.
> 
> Refer to [`libkeycloak.sh`](https://github.com/bitnami/bitnami-docker-keycloak/blob/master/11/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh) for the related logic that checks for DB availability and configures the connection to the application.

I want to submit a pull request for this. Are the MySQL drivers available on https://downloads.bitnami.com/files/stacksmith for me to use in libcomponent.sh or do i have to use a different source for embedding the drivers in the image?

**Comment by marcosbc** [comment]
@vrtata That is great! You can use mysql-client from [`bitnami-docker-wordpress`](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/Dockerfile#L15), for instance. By including that component and [`mysql-client` files from `rootfs`](https://github.com/bitnami/bitnami-docker-wordpress/tree/master/5/debian-10/rootfs/opt/bitnami/scripts), plus any required `mysql-client` system packages, you should be able to get a working image without problems.
