### ISSUE TITLE
Missing Volume for service 

### ISSUE THREAD

**Issue by sunflowerno0b** [bitnami/bitnami-docker-keycloak#42]
**Description**

Trying to spin up a new keycloak but I get an error on my volumes. Trying to figure out what is missing :/ 
**Steps to reproduce the issue:**

1. [First Step]
run `docker-compose up` within directory where my docker-compose file is 
2. [Second Step]
I get the error.

**Describe the results you received:**
See attachement.

See attachment. 
**Describe the results you expected:**
Access to keycloak.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
(Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 14
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-1021-aws
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.688GiB
 Name: ip-172-31-43-147
 ID: HRHT:Q3BP:YHMS:JXEV:IAIY:XR7R:4SLY:MBGG:L3LF:M76W:KDAX:D4RC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBo
![Screen Shot 2022-01-05 at 1 39 10 PM](https://user-images.githubusercontent.com/68705196/148271260-87ccbef4-eb95-4f1b-8df9-d153edf3479b.png)
x, Docker for MAC, physical, etc.):**
AWS, local.

**Comment by carrodher** [comment]
I'm not able to reproduce the issue by using the _docker-compose.yaml_ present in the root of this repository. Can you share what are the customizations you did based on that file? What are the differences?

**Comment by sunflowerno0b** [comment]
i think its because i am missing the volume section - could you share some configuration options for the volume to tie back to service postgresql?

**Comment by carrodher** [comment]
You can check the _docker-compose.yaml_ present in the root of this repository

**Comment by sunflowerno0b** [comment]
thanks, ive added 

```
volumes:
  postgresql_data:
    driver: local
```

but I get the following error (see attached)

![Screen Shot 2022-01-07 at 12 15 37 PM](https://user-images.githubusercontent.com/68705196/148581262-5fc4716f-b742-4bb1-a835-46446c2b1c02.png)

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami keycloak container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
