### ISSUE TITLE
Include the possibility to connect other databases, not only PostgreSQL

### ISSUE THREAD

**Issue by acidicX** [bitnami/bitnami-docker-keycloak#45]
**Description**

As keycloak supports other DBs and the [jboss image](https://registry.hub.docker.com/r/jboss/keycloak#!) also supports switching DBMS via ENV (DB_VENDOR), it would be a good addition to also use the ENV in this image, and also add it to the chart (https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml#L927 - "externalDatabase").

It currently does not work.

**Steps to reproduce the issue:**

1. add `KEYCLOAK_DB_VENDOR=mysql` as ENV
2. run the image

**Describe the results you received:**

Container tries to connect to a PostgreSQL with the given host and credentials

**Describe the results you expected:**

Container should connect to mysql

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

docker / kubernetes

**Comment by carrodher** [comment]
Thanks for this suggestion!
Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback.

**Comment by acidicX** [comment]
@carrodher there already is a PR #26 - but that would need to be merged. I didn't see the PR before creating the issue.
