### ISSUE TITLE
Keycloak image won't start on an M1 Apple Silicon macOS device due to a script abort.

### ISSUE THREAD

**Issue by doctorpangloss** [bitnami/bitnami-docker-keycloak#47]
### Name and Version

bitnami/keycloak:16.1.0

### What steps will reproduce the bug?

1. Try to start `bitnami/keycloak:16.1.0` on an M1 Apple Silicon macOS device as an `amd64` image running under Rosetta.
2. Observe the following logs in the container:
```
keycloak 18:57:55.96 
keycloak 18:57:55.99 Welcome to the Bitnami keycloak container
keycloak 18:57:56.01 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-keycloak
keycloak 18:57:56.03 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-keycloak/issues
keycloak 18:57:56.05 
keycloak 18:57:56.07 INFO  ==> ** Starting keycloak setup **
keycloak 18:57:56.19 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 18:57:56.34 INFO  ==> Trying to connect to PostgreSQL server xxx_postgres...
keycloak 18:57:56.45 INFO  ==> Found PostgreSQL server listening at xxx_postgres:5432
keycloak 18:57:56.53 INFO  ==> Configuring database settings
/opt/bitnami/scripts/libos.sh: line 336:    89 Aborted                 "$@" > /dev/null 2>&1
```

### What is the expected behavior?

The container should start in this environment.

### What do you see instead?

There's an abort in a script.

### Additional information

The rebuilt Apple Silicon images hosted by a community user starts, but they have other flaws.

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
