### ISSUE TITLE
Documentation Uncertainty about how Bitnami/Keycloak is implementing TLS/SSL

### ISSUE THREAD

**Issue by lonniev** [bitnami/bitnami-docker-keycloak#5]
This is not a bug report and so I removed the expected/encountered template.

The KeyCloak documentation claims that the following stanza is to be added to the `standalone.xml` or `standalone-ha.xml` configuration in order to configure the Keycloak service to use TLS/SSL.

`<security-realms>
    <security-realm name="ssl-realm">
        <server-identities>
            <ssl>
                <keystore path="servercert.jks"
                          relative-to="jboss.server.config.dir"
                          keystore-password="servercert password"/>
            </ssl>
        </server-identities>
        <authentication>
            <truststore path="truststore.jks"
                        relative-to="jboss.server.config.dir"
                        keystore-password="truststore password"/>
        </authentication>
    </security-realm>
</security-realms>`

However, the bitnami documentation on TLS support does not mention this configuration edit and its version of `standalone-ha.xml` does not have that stanza added to it. Nevertheless, the running Keycloak server is listening with a TLS server at the chosen port using the provided truststore and keystore.

Implication: the original Keycloak documentation is out-of-date and whatever is found in the running `standalone-ha.xml` is what is necessary to have Keycloak use TLS/SSL for itself, with peer servers, with "Client Applications", and with users interacting through Authentication Flows.

Request: could the bitnami documentation on TLS/SSL be expanded to advise ways to assure that the Keycloak service is operating with the configuration desired and attempted?

This is especially useful as one attempts to diagnose why complex x.509 user authentication flows are not working. Those are full of potentially misconfigurations and there is little advice on how to diagnose them.

**Comment by miguelaeh** [comment]
Hi @lonniev ,
You can see here how we are configuring the TLS: https://github.com/bitnami/bitnami-docker-keycloak/blob/master/12/debian-10/rootfs/opt/bitnami/scripts/libkeycloak.sh#L235
