### ISSUE TITLE
Debian 11 (Bullseye) support

### ISSUE THREAD

**Issue by day1118** [bitnami/bitnami-docker-keycloak#52]
### Name and Version

bitnami/keycloak:16.1.1-debian-10

### What is the problem this feature will solve?

There are a large number of known vulnerabilities in `docker.io/bitnami/minideb:buster` which are not planned to be fixed at this time.
```console
$ docker run --rm aquasec/trivy image --vuln-type os docker.io/bitnami/minideb:buster
INFO	Detected OS: debian
INFO	Detecting Debian vulnerabilities...
docker.io/bitnami/minideb:buster (debian 10.12)
===============================================
Total: 125 (UNKNOWN: 0, LOW: 83, MEDIUM: 13, HIGH: 21, CRITICAL: 8)
```

```console
$ docker run --rm aquasec/trivy image --vuln-type os docker.io/bitnami/minideb:bullseye
INFO	Detected OS: debian
INFO	Detecting Debian vulnerabilities...
docker.io/bitnami/minideb:bullseye (debian 11.3)
================================================
Total: 67 (UNKNOWN: 0, LOW: 60, MEDIUM: 3, HIGH: 4, CRITICAL: 0)
```

### What is the feature you are proposing to solve the problem?

Move the base image to use `docker.io/bitnami/minideb:bullseye`
Is this planned? Do you have a time frame in mind?

### What alternatives have you considered?

Maintaining a separate fork

**Comment by carrodher** [comment]
Thanks for the suggestion. This topic is in our roadmap, but due to other priorities the team has, I can't provide an ETA at this moment
