### ISSUE TITLE
Configuration from a Docker Host's standalone-ha.xml mounted file

### ISSUE THREAD

**Issue by lonniev** [bitnami/bitnami-docker-keycloak#6]
**Description**

Wanting to force user-clients to have to supply SSL certificates, I learn that the `want-client-auth` attribute of the `ssl-context` should be replaced with `need-client-auth="true"`.

I attempt to edit the `/opt/bitnami/keycloak/standalone/configuration/standalone-ha.xml` file within the container and discover that the linux environment therein lacks any editor and that the configuration file gets generated during restart anyway.

So I read the README here and it states that configuration files can be mounted from the Docker Host into the container with a read-only volume mount.

I attempt that.

On container restart, the service fails to start because the bitnami startup script finds it can no longer remove the configuration file.

**Steps to reproduce the issue:**

1. [First Step]
git clone && docker-compose up. Just try to run the shrink-wrapped experience.

2. [Second Step]
Read the README and alter the docker-compose.yml so that a suitable standalone-ha.xml file is volume-mounted-readonly into the container where it expects to find the file.

3. [and so on...]
docker-compose down
docker-compose up

**Describe the results you received:**

docker logs bit-keycloak --tail 50 -f
keycloak 20:32:29.29 
keycloak 20:32:29.31 Welcome to the Bitnami keycloak container
keycloak 20:32:29.32 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-keycloak
keycloak 20:32:29.33 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-keycloak/issues
keycloak 20:32:29.34 
keycloak 20:32:29.34 INFO  ==> ** Starting keycloak setup **
keycloak 20:32:29.40 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 20:32:29.50 INFO  ==> Removing configuration file
rm: cannot remove '/opt/bitnami/keycloak/standalone/configuration/standalone-ha.xml': Device or resource busy

**Describe the results you expected:**

nice log showing the server initialization running to completion and the HTTPS listener becoming available in the browser - as it all did with the shrink-wrapped experience.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
✗ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
```

- Output of `docker info`:

```
✗ docker inspect bitnami/keycloak:latest
[
    {
        "Id": "sha256:743ca1dd54ebb9d6800ab03aeacad174708b2c9a95973ba0d3d0103440798b0f",
        "RepoTags": [
            "bitnami/keycloak:latest"
        ],
        "RepoDigests": [
            "bitnami/keycloak@sha256:36eb63138c4f0e0d251235c6fcd5058094184028a79bc5682b6638a35d4ef683"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2021-01-24T19:42:49.931830569Z",
        "Container": "c435e4c2476494d14392807f4824e063c92e1f07a5b6eebf5a99bebc25a8a514",
```

- Output of `docker-compose version` (if applicable):

```
✗ docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

MacOS, BigSur

**Comment by juan131** [comment]
Hello @lonniev 

As it's described in the link below, the mountpath where you should mount your custom configuration file is `/bitnami/keycloak/configuration/standalone-ha.xml`, see:

- https://github.com/bitnami/bitnami-docker-keycloak#full-configuration

Could you please double-check that you're mounting it there?
Could you share the Docker Compose you're using (after your modifications)?
