### ISSUE TITLE
Keycloak refuses to start with prod profile if TLS disabled even when proxy mode is set to edge 

### ISSUE THREAD

**Issue by AndreaVida** [bitnami/bitnami-docker-keycloak#60]
### Name and Version

bitnami/keycloak:18.0.0-debian-10-r0

### What steps will reproduce the bug?

Run the image with following env vars:

```shell
KEYCLOAK_ENABLE_TLS: "false"
KEYCLOAK_PRODUCTION: "true"
KEYCLOAK_PROXY: "edge"
```

### What is the expected behavior?

According to [reverse proxy guide](https://www.keycloak.org/server/reverseproxy), **edge** proxy mode "is suitable for deployments where the reverse proxy keeps a secure connection (HTTP over TLS) with clients while communicating with Keycloak using HTTP". 
Expected behavior would then be to allow production profile to be used when KEYCLOAK_ENABLE_TLS="false" and KEYCLOAK_PROXY="edge".

### What do you see instead?

```shell
keycloak 09:31:42.65 Welcome to the Bitnami keycloak container
keycloak 09:31:42.66 INFO  ==> ** Starting keycloak setup **
keycloak 09:31:42.69 INFO  ==> Validating settings in KEYCLOAK_* env vars...
keycloak 09:31:42.69 ERROR ==> You need to have the TLS enable. Please set the KEYCLOAK_ENABLE_TLS variable to true
```

**Comment by jack1902** [comment]
@AndreaVida ran into this myself, take a look at https://github.com/bitnami/charts/issues/10236 since I ended up overriding the default CMD and ENTRYPOINT in the container to overcome this

**Comment by KaiserMarvin** [comment]
I ran into this myself too.

**Comment by AndreaVida** [comment]
Hi @dgomezleon,

I understand TLS requirement but to be noted that at the beginning of that guide they also mention that ```This information focuses on the general concepts instead of the actual implementation, which depends on your environment```.

In fact, there are many other ways of securing communications with TLS other than having KC itself doing that job. For example, in our Kubernetes environment we have Istio ingress gateway acting as reverse proxy and TLS termination, plus mTLS encryption on all Pods internal network traffic. We do not need to add yet another encryption layer between gateway and KC but we do need to be able to start KC in production profile.

Also, KC documentation itself seems to support this kind of configuration with a [reverseproxy](https://www.keycloak.org/server/reverseproxy) (proxy mode = edge).

Moreover, @jack1902 also stated in [issue 10236](https://github.com/bitnami/charts/issues/10236#issuecomment-1130305482) that ```you can run kc.sh start without passing any TLS flags, and it doesn't blow up asking for TLS to be configured meaning it is optional```

**Comment by jack1902** [comment]
@dgomezleon would the changes to the underlying scripts remove the need for the `KEYCLOAK_PRODUCTION` env-var so that `start` runs as the default command without forcing TLS ?

I've had a length issue around this on the helm-chart that uses this image here: https://github.com/bitnami/charts/issues/10236

I'd be happy to raise a pr to address it so that the caller can use `tls` if they wish but things startup as "prod" by default (there can be a "dev-mode" flag to use `start-dev` as the alternative?

I'd rather reach a consensus around it first before implementation if that makes sense?

**Comment by jack1902** [comment]
Thinking it through, it might be worthy to have the script be more aware of the `proxy` mode enabled. Making decisions based on the users input:
- `edge` - Don't use any `tls` flags passed, don't blow up if TLS isn't passed
- `reencrypt` / `passthrough` - Expect `tls` flags / settings to be present. If not present, blowup

This makes the scripts more aware of the `proxy` settings whilst also ensuring the use-cases of end-users are met with logical reasoning based on the `proxy` mode configured. Adding `KEYCLOAK_DEV_MODE` or something to enable someone to use `start-dev` then allows for all cases whilst ensuring the default path is Prod mode `start`

**Comment by marrws** [comment]
> @marrws, would you like to contribute with a PR addressing the changes? Could you also please check if you are able to access the admin console via UI. It seems this validation was added due to issues accessing admin console on production mode without TLS.

We would gladly send a PR for this since we already have the modifications internally.

@jack1902 We're now running `passthrough` without TLS [^1] so we're more into _let users choose their preferred proxy mode_ instead of adding more logic to `libkeycloak.sh`

[^1]: cc my coworker @abrahamjoc who made this change

**Comment by marrws** [comment]
PR #68 solves this issue

**Comment by dgomezleon** [comment]
Thanks a lot for the contribution @jack1902 and @marrws . The team will check your PR.
