### ISSUE TITLE
KEYCLOAK_DATABASE_SCHEMA is ignored when defined in postgres DB type

### ISSUE THREAD

**Issue by tapionff** [bitnami/bitnami-docker-keycloak#61]
### Name and Version

bitnami/keycloak:18-debian-10

### What steps will reproduce the bug?

1. use bitnami helm chart bitnamin/keycloak version 9.0.0 to deploy bitnami/keycloak:18-debian-10 as image
2. add in values an extraEnvVar with the desired schema 
    ```extraEnvVars:
        -   name: KEYCLOAK_DATABASE_SCHEMA
            value: mycustom_schema
     ``` 
3. deploy chart and check logs and see db-url ->jdbc:postgresql://myip:5432/mydb" without the defined schema

### What is the expected behavior?

It is expected to get the db-url set with currentSchema defined in environment variables
db-url ->jdbc:postgresql://myip:5432/mydb?currentSchema=mycustom_schema

### What do you see instead?

The db-url connection do not contains defined SCHEMA
db-url ->jdbc:postgresql://myip:5432/mydb"

**Comment by rafariossaa** [comment]
Hi,
  Thanks for submitting a PR to fix it.
  Let's wait until it get reviewed and merged.

**Comment by alemorcuq** [comment]
Tags `18.0.0-debian-10-r6` and `17.0.1-debian-10-r11` include the change.
