### ISSUE TITLE
M1 Macbook Pro - Gets stuck on configuring

### ISSUE THREAD

**Issue by dimitur2204** [bitnami/bitnami-docker-keycloak#67]
### Name and Version

bitnami/keycloak:15

### What steps will reproduce the bug?

1. Running a M1 Pro Macbook Pro 16 inch, 16GB of RAM.
2. This is the `docker-compose`
```  ## Postgres Development ##
  ##########################
  pg-db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME?}-pg-db
    restart: always

    volumes:
      - pg-db-data:/bitnami/postgresql

    ports:
      - 5432:5432

    environment:
      ## https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md
      PGPASSWORD: ${DB_PASS?}
      POSTGRESQL_USERNAME: ${DB_USER?}
      POSTGRESQL_PASSWORD: ${DB_PASS?}
      POSTGRESQL_DATABASE: ${DB_NAME?}

    networks:
      - backend-net

  ########################################
  ## LOCAL IDENTITY PROVIDER - KEYCLOAK ##
  ########################################

  ## Keycloak Database  ##
  ########################
  keycloak-db:
    container_name: ${COMPOSE_PROJECT_NAME?}-keycloak-db
    image: docker.io/bitnami/postgresql:13
    profiles: ['local-keycloak']
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'keycloak-db-data:/bitnami/postgresql'
    networks:
      backend-net:

  ## Keycloak Server ##
  #####################
  keycloak:
    container_name: ${COMPOSE_PROJECT_NAME?}-keycloak
    image: docker.io/bitnami/keycloak:15
    profiles: ['local-keycloak']
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_EXTRA_ARGS=-Dkeycloak.import=/opt/bitnami/keycloak/config/keycloak-webapp-realm.json
      - DEBUG=true
      - DEBUG_PORT='*:8787'
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-db
      - DB_DATABASE=bitnami_keycloak
      - DB_USER=bn_keycloak
      - TZ=Europe/Sofia
    depends_on:
      - keycloak-db
    ports:
      - '8180:8080'
      - '8787:8787'
    volumes:
      - './manifests/keycloak/theme_podkrepi:/opt/bitnami/keycloak/themes/theme_podkrepi'
      - './manifests/keycloak/config:/opt/bitnami/keycloak/config'
    networks:
      backend-net:

volumes:
  pg-db-data:
  keycloak-db-data:
    driver: local 

networks:
  backend-net:
```

4. Run `docker-compose up --build -d pg-db keycloak keycloak-db`
5. Never manages to start!

### What is the expected behavior?

The expected behaviour is that it should be able to start :D. I've left it for hours and it never started

### What do you see instead?

It always gets stuck on either `Configuring database settings` or `Configuring log level`
<img width="899" alt="image" src="https://user-images.githubusercontent.com/61479393/169646768-34a60962-57e9-4ca4-bba9-d46c6a055648.png">

### Additional information

It is because of the arm64 architecture of the machine. I've had problems with many images before not related to bitnami.
However there is one image for Keycloak that I am currently using that works. If it helps you can take a look at it :) [dcm4che/keycloak](https://hub.docker.com/r/dcm4che/keycloak)

**Comment by carrodher** [comment]
Hi, at this moment, ARM64 is not supported. We have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by dimitur2204** [comment]
> Hi, at this moment, ARM64 is not supported. We have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.
> 
> We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

Ok good one 😃!
