### ISSUE TITLE
cache-stack: ability to specify

### ISSUE THREAD

**Issue by jack1902** [bitnami/bitnami-docker-keycloak#69]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

To enable the user of the image to specify their desired cache stack when running multiple replicas of Keycloak. 

### What is the feature you are proposing to solve the problem?

Currently, it falls to the default cache-stack which is UDP but there are more optimal settings which enable keycloak to utilize information stored within a headless service within kubernetes for example.

This can be achieved by called `kc.sh build --cache-stack=<STACK>

More info: https://www.keycloak.org/server/caching

### What alternatives have you considered?

Overriding the default entry point/args via the helm-chart but having an "official" way of configuring the cache stack would be useful.

I've had it working by using this snippet into the helm-chart: https://github.com/bitnami/charts/issues/10236#issuecomment-1128858062

**Comment by javsalgar** [comment]
Hi,

I'd say that the official way to set it would be allowing an environment variable that is used in the keycloak_initialize function in libkeycloak.sh. Something like `KEYCLOAK_CACHE_STACK` for example. Would you like to contribute with a PR?

**Comment by marrws** [comment]
This was added in #65 (merged) and deleted by bitnami bot in the latest build:

Keycloak 17:
https://github.com/bitnami/bitnami-docker-keycloak/commit/f735607283b42c7bdc09c6f73fd3942ab032d0ff#diff-de145994615faa811c28e976d839ef3e2b8bfb81a49e941f7447f5f05e84cd4aL142

Keycloak 18:
https://github.com/bitnami/bitnami-docker-keycloak/commit/5348075f8c76cfa1e2dbe694a25fc057b5cec5fd#diff-d00d1973cb53ee465af285614b157b5e7bb72e9c6a46a4ffa038b80c06dddf48L142

**Comment by marrws** [comment]
sorry to tag you @migruiz4 but since you merged #65, do you have a clue of what might have happened with the bot?

**Comment by marrws** [comment]
We restored this line in `libkeycloak.sh`:

```! is_empty_value "$KEYCLOAK_CACHE_STACK" && debug_execute kc.sh build --cache-stack="${KEYCLOAK_CACHE_STACK}"```

Then enabled cache using the chart and `cache.enabled`[^1]. Everything works as expected, we have distributed cache and the cache stack is `kubernetes`.

[^1]: bitnami/charts#10387

**Comment by jack1902** [comment]
I've raised https://github.com/bitnami/bitnami-docker-keycloak/pull/73 to add it back, as not having it in the repo is slightly confusing
