### ISSUE TITLE
Can't run Keycloak in OpenShift

### ISSUE THREAD

**Issue by holzman** [bitnami/bitnami-docker-keycloak#78]
### Name and Version

bitnami/keycloak

### What steps will reproduce the bug?

Deploying Bitnami keycloak (via helm chart) on OpenShift.

### What is the expected behavior?

keycloak start up successfully

### What do you see instead?

`/opt/bitnami/scripts/libfile.sh: line 39: /opt/bitnami/keycloak/conf/keycloak.conf: Permission denied`

### Additional information

Keycloak's post-unpack script does a chown of `/opt/bitnami/keycloak` based on `KEYCLOAK_DAEMON_USER` and `KEYCLOAK_DAEMON_GROUP`, which are set to `keycloak` by default but are mode 770.  Containers in openshift run by default with an ephemeral uid, and gid 0. 

One potential solution is to add `ARG KEYCLOAK_DAEMON_GROUP=0` to the Dockerfile before the postunpack scripts get called.

**Comment by rafariossaa** [comment]
Hi,
  I am taking a look to this. Thanks for reporting it
