### ISSUE TITLE
Enable Keycloak metrics in the docker image

### ISSUE THREAD

**Issue by harishdesetti1206** [bitnami/bitnami-docker-keycloak#80]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Want to scrape the fine grained metrics of the keycloak actions.

### What is the feature you are proposing to solve the problem?

I created this issue to consult for a feature related to Keycloak metrics. I know that the keycloak statistics are exposed when we enable the flag **KEYCLOAK_ENABLE_STATISTICS**. But it would be so great if we could scrape the fined-grained metrics of keycloak.

Can we enable the metrics that are exposed by [jar](https://github.com/aerogear/keycloak-metrics-spi) in the docker image?

The reason for bringing up this is :
1. The enabling is pretty simple, add 2 flags ENV KC_HEALTH_ENABLED,ENV KC_METRICS_ENABLED in the [keycloak_env_vars](https://github.com/bitnami/bitnami-docker-keycloak/blob/master/18/debian-10/rootfs/opt/bitnami/scripts/keycloak-env.sh).
2. Place the jar under the directory /opt/bitnami/keycloak . Even the size of the jar is just 0.2MB.

I'm proposing this idea after discussing it with my team @abrahamjoc @marrws

**Imp Ref**: https://www.keycloak.org/server/containers

**Comment by harishdesetti1206** [comment]
Adding to this, we can always use a flag to enable these metrics. (No need to force user to expose the metrics by default)

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but we are only adding official metrics to our assets.
 The reason is that in the past we had unofficial exporters that got abandoned and we had to remove them because they got unmaintained (security bugs, no update to new versions, etc).
