### ISSUE TITLE
Provide documentation for updating the root path of keycloak

### ISSUE THREAD

**Issue by DavidKittleSEL** [bitnami/bitnami-docker-keycloak#84]
### Name and Version

bitnami/keycloak:18.0.0-debian-11-r2

### What is the problem this feature will solve?

Previous versions (16.x) of keycloak defaulted to a root path of "/auth". The current (18.x) switched to using a root path of "/". Due to the nature of the new quarkus runtime I believe changing the root path is a build time option. But I haven't found any documentation on how to acomplish this task. 

### What is the feature you are proposing to solve the problem?

Provide documentation oh how to build keycloak container images with custom options, similar to what redhat has: https://www.keycloak.org/server/containers#_building_your_optimized_keycloak_docker_image

### What alternatives have you considered?

I tried following the steps in redhat's documentation https://www.keycloak.org/server/containers#_building_your_optimized_keycloak_docker_image, but the bitnami version of the keycloak container image moved things around and uses different scripts.

**Comment by marcosbc** [comment]
Hi @DavidKittleSEL, this seems like a question more related to the functionality of the Keycloak software, rather than the Bitnami container configuration. I encourage you to open a new issue in the [official Keycloak repository](https://github.com/keycloak/keycloak) to resolve this issue.

**Comment by DavidKittleSEL** [comment]
The issue isn't missing functionality from the parent keycloak project, they actually have a [documented ](https://www.keycloak.org/server/containers#_building_your_optimized_keycloak_docker_image)way to change keycloak's URL base path. The problem is non of that documentation is applicable to this container image, since it utilizes completely different entrypoint/startup scripts. After spending some time familiarizing myself with the various scripts in this container image, I have come to realize this is less an issue of documentation and more an issue of missing functionality. There is no way to configure keycloak's URL base path. However it does seem there is a [PR](#75) up to address this issue. Feel free to link this issue to that PR and close this one.

**Comment by marcosbc** [comment]
That's great! This is the PR link: #75. Proceeding to closing this.
