### ISSUE TITLE
keycloak-config-cli for 13.X keycloak

### ISSUE THREAD

**Issue by lukasmrtvy** [bitnami/bitnami-docker-keycloak#9]
We need to publish different flavours of keycloak-config-cli, this one is apparently for keycloak 12.X ( https://github.com/adorsys/keycloak-config-cli/issues/414#issuecomment-846472237 ), otherwise one will have a problem in current helm chart based on keycloak image 13.0.0-debian-10-r1 ( https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml#L50 ) and on keycloak-config-cli image 3.4.0-debian-10-r1 ( https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml#L758 )

Related:
https://github.com/adorsys/keycloak-config-cli/issues/414

Thanks

**Comment by marcosbc** [comment]
Hi @lukasmrtvy, we include the JARs for all supported `keycloak-config-cli` versions in the container image:

```
$ find /opt/bitnami/keycloak-config-cli -name '*.jar'
/opt/bitnami/keycloak-config-cli/keycloak-config-cli-11.0.3.jar
/opt/bitnami/keycloak-config-cli/keycloak-config-cli-13.0.0.jar
/opt/bitnami/keycloak-config-cli/keycloak-config-cli-9.0.3.jar
/opt/bitnami/keycloak-config-cli/keycloak-config-cli.jar
/opt/bitnami/keycloak-config-cli/keycloak-config-cli-12.0.4.jar
/opt/bitnami/keycloak-config-cli/keycloak-config-cli-10.0.2.jar
```

By default, the container image is [configured to use the non-versioned JAR file](https://github.com/bitnami/bitnami-docker-keycloak-config-cli/blob/master/3/debian-10/Dockerfile#L29) (which is symlink to version 12). If you wish to use a different version, you need to override the entrypoint for the container. If using the chart, try setting `keycloakConfigCli.command` to point to `/opt/bitnami/keycloak-config-cli/keycloak-config-cli-13.0.0.jar`.
